name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: ${{ secrets.SSH_HOST_NGINX }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY_NGINX }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ${{ secrets.NGINX_ENDPOINT_RUNNER }}
          append: |
            - endpoint: ${{ secrets.NGINX_ENDPOINT_ARM64 }}
              platforms: linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push (Nginx With nginx-ngx_immutable)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            navystack/nginx-ngx_immutable:dev
            navystack/nginx-ngx_immutable:mainline
            navystack/nginx-ngx_immutable:1.25.3
            navystack/nginx-ngx_immutable:latest
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: ${{ secrets.BUILD_CACHE_FROM }}
          cache-to: ${{ secrets.BUILD_CACHE_TO }}
